### ISSUE TITLE
delete the whole bot and write it again

### ISSUE THREAD

**Issue by sentriz** [cpssd-students/steely#84] opened 2017-09-28 14:50 UTC
BOLD bot
BAD

**Comment by byxor** [comment] 2017-09-29 13:27
Is there a hint of seriousness in this? So far the bot has been pretty easy to write plugins for.

**Comment by izaakf** [comment] 2017-09-29 22:58
I'm super tempted to re-write steely tomorrow

**Comment by sentriz** [comment] 2017-09-29 23:44
eh it could be a lot better. I'll be happy if I can do that decorator/pipeline thing

**Comment by devoxel** [comment] 2017-09-30 10:02
If we want to implement sep1 nicely we need to break sep1 into a few issues and get going

**Comment by byxor** [comment] 2017-09-30 19:54
Don't rewrite, you'll run into the same rigidity problems unless you test it properly.

**Comment by izaakf** [comment] 2017-10-03 21:54
Okay, so I re-wrote steely. The code is perfect. It's written in PyRuby. I'll put it up tomorrow after this repo is rm'ed

**Comment by iandioch** [comment] 2017-10-28 23:39
NC as I will show this to DH to vindicate my rightness grin

I just asked DH where the cat was - "she's standing at the front gate" apparently hmm

Is it just me, or can cats not actually stand? Only people with two legs can stand, surely. Cats can't stand. DH is clearly BU. 

What would we say instead of standing, though? 

Don't let me down MNers. Cats can't stand. Or can they?

**Comment by byxor** [comment] 2017-10-29 01:15
Birds are flyin' south for winter.

Here's the Weird-Bird headin' north,
Wings a-flappin', beak a-chatterin',
Cold head bobbin' back 'n' forth.

He says, "It's not that I like ice
Or freezin' winds and snowy ground.

It's just sometimes it's kind of nice
To be the only bird in town.
"

**Comment by byxor** [comment] 2017-11-27 15:31
Genius, like gold and precious stones, 
is chiefly prized because of its rarity.
 

Geniuses are people who dash of weird, wild, 
incomprehensible poems with astonishing facility, 
and get booming drunk and sleep in the gutter.
 

Genius elevates its possessor to ineffable spheres 
far above the vulgar world and fills his soul 
with regal contempt for the gross and sordid things of earth.
 

It is probably on account of this 
that people who have genius 
do not pay their board, as a general thing.
 

Geniuses are very singular.
 

If you see a young man who has frowsy hair 
and distraught look, and affects eccentricity in dress, 
you may set him down for a genius.
 

If he sings about the degeneracy of a world 
which courts vulgar opulence 
and neglects brains, 
he is undoubtedly a genius.
 

If he is too proud to accept assistance, 
and spurns it with a lordly air 
at the very same time 
that he knows he can't make a living to save his life, 
he is most certainly a genius.
 

If he hangs on and sticks to poetry, 
notwithstanding sawing wood comes handier to him, 
he is a true genius.
 

If he throws away every opportunity in life 
and crushes the affection and the patience of his friends 
and then protests in sickly rhymes of his hard lot, 
and finally persists, 
in spite of the sound advice of persons who have got sense 
but not any genius, 
persists in going up some infamous back alley 
dying in rags and dirt, 
he is beyond all question a genius.
 

But above all things, 
to deftly throw the incoherent ravings of insanity into verse 
and then rush off and get booming drunk, 
is the surest of all the different signs 
of genius.

**Comment by iandioch** [comment] 2018-02-16 12:24
This bug is still affecting me. Reopening the issue.

**Comment by byxor** [comment] 2018-02-16 13:36
The worm can turn;
Haven’t you heard?
When you think upon it
It seems absurd.
Worms can turn near,
Worms can turn far,
It really depends
On where they are.
Worms are turning
Everywhere.
One might be turning
In your hair.
Worms in an apple
Find turning hell:
‘Cause apples are hard,
They can’t turn very well.

**Comment by byxor** [comment] 2018-02-16 13:36
Oh, I’m an un-vegetarian:
I love to eat real meat.
I’d rather eat a roasted lamb
Than stuff that’s made of wheat.

I shape my beef as carrots,
Make chicken look like peas;
I flavor it to taste like them
To hide carnivorous needs.

**Comment by sentriz** [comment] 2018-02-16 13:37
now #84 I can get into

**Comment by iandioch** [comment] 2019-01-20 01:20
h-hi, can i give this issue a go~~?

**Comment by sentriz** [comment] 2019-01-21 15:18
@iandioch absolutely yes please

**Comment by iandioch** [comment] 2020-10-13 21:47
dupe of #138

**Closed by iandioch** 2020-10-13 21:47 UTC
Labels: enhancement
