### ISSUE TITLE
Refactor .gex

### ISSUE THREAD

**Issue by iandioch** [cpssd-students/steely#83] opened 2017-09-27 21:07 UTC
This craic is a mess. Who wrote this? It's all over the place.

**Comment by byxor** [comment] 2017-09-28 13:10
https://simpleprogrammer.com/2010/10/01/living-dangerously-refactoring-without-a-safety-net/

**Comment by iandioch** [comment] 2017-09-28 13:31
Tests would be desirable. I should refactor this code to make it more easily testable.

**Comment by iandioch** [comment] 2017-09-28 13:31
Good idea.

**Comment by sentriz** [comment] 2017-09-28 14:51
duplicate of https://github.com/sentriz/steely/issues/84

**Closed** 2020-10-13 21:48 UTC
